### ISSUE TITLE
Coverage Pool v1.0.0 deployment

### ISSUE THREAD

**Issue by pdyraga** [keep-network/coverage-pools#125]
Team | Members
------------ | -------------
**Deployment Team** | `0x123694886DBf5Ac94DDA07135349534536D14cAf`
**Technical Wallet Team** | `0xB3726E69Da808A689F2607939a2D9E958724FC2A`
**Community Multisig** | `0x19FcB32347ff4656E4E6746b4584192D185d640d`
**Reward Manager** | `0xb78c0cf4c9e9bf4ba24b17065fa8c0ac71957653`
**Communications** | TBD

# Prerequisites
- [x] Determine initial auction length (https://github.com/keep-network/coverage-pools/issues/126)
- [x] Deployment scripts ready
- [x] All security audit issues addressed

# Deploy smart contracts
All steps done by Deployment Team
- [x] Tag `solidity/v1.0.0` in `keep-network/coverage-pools`
- [x] Sign `solidity/v1.0.0` commit hash
- [x] Deploy `UnderwriterToken` contract (address: `0x2Aa24DAc5E494e7B028ED43023530E5769df5D8b`) with the following parameters:
  - `_name`: `covKEEP underwriter token`
  - `_symbol`: `covKEEP`
- [x] Deploy `AssetPool` (address: `0x2ada2d985Ce69b467d2D8372494Df021BEDfdbf2`) with the following parameters:
  - `_collateralToken`: `KEEP@0x85eee30c52b0b379b046fb0f85f4f3dc3009afec`
  - `_underwrtierToken`: `UnderwriterToken.address` (deployed in previous step)
  - `rewardsManager`: Deployment Team (temporarily, will be transferred in next steps)
- [x] Deploy `CoveragePool` (address: `0x91cd77a78de10e9df7538270b324a8a8be3bf877`) with the following parameters:
  - `_assetPool`: `AssetPool.address` (deployed in previous step)
- [x] Deploy `AuctionBidder` (address: `0x773A4cACbcA8e3704F8f7842531eAb83e437B3C4`) with the following parameters:
  - `_coveragePool`: `CoveragePool.address` (deployed in previous step)
- [x] Deploy `SignerBondsManualSwap` (address: `0x43faf6fe84e01dd186cfeb9ea2f0854a1ef7442f`)
- [x] Deploy `SignerBondsUniswapV2`  (address: `0x9f054B7EaEEE0011A3bF3eAe38E73fb7A37e1eAe`) with the following parameters:
  - `_uniswapRouter`: `UniswapV2Router02@0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D`
  - `_coveragePool`: `CoveragePool.address`
- [x] Deploy master `Auction` contract (address: `0xAbe0080eA5F7A58b90398B1c87093CC225E33fE1`)
- [x] Deploy `RiskManagerV1`  (address: `0x2355d701D8d85eD161AB66a0A7e759C463F62b30`) with the following parameters:
  - `_tbtcToken`: `TBTC@0x8dAEBADE922dF735c38C80C7eBD708Af50815fAa`
  - `_tbtcDepositToken`: `TDT@0x10b66bd1e3b5a936b7f8dbc5976004311037cdf0`
  - `_coveragePool`: `CoveragePool.address`
  - `_signerBondsSwapStrategy`: `SignerBondsUniswapV2.address`
  - `_masterAuction`: master `Auction.address`
  - `_auctionLength`: `604800`
  - `_bondAuctionThreshold`: `100`
- [x] Deploy `CoveragePoolBeneficiary` beneficiary (address: `0x22428b09efC87709ab49a77da6F9CE4FfA2ee39b`) with the following parameters:
  - `token`:  `KEEP@0x85eee30c52b0b379b046fb0f85f4f3dc3009afec`
  - `rewards`: `assetPool.rewardsPool().address`
- [x] Transfer `UnderwriterToken` ownership to `AssetPool`
- [x] Transfer `AssetPool` ownership to `CoveragePool`
- [x] Transfer `RewardsPool` ownership to `CoveragePoolBeneficiary`
- [x] Transfer ownership of `CoveragePoolBeneficiary` to `BatchedPhasedEscrow@0x1b8e50ec9fbf844c3671bc178df8eadfcff831ca`.
- [x] Transfer ownership of `SignerBondsUniswapV2` ownership to Keep Community Multisig
- [x]  Transfer ownership of `SignerBondsManualSwap` to Keep Community Multisig
- [x] Transfer `CoveragePool` ownership to Keep Community Multisig
- [x] Transfer `RiskManagerV1` ownership to Keep Community Multisig

 # Etherscan verification
All steps done by Deployment Team
- [x] Verify `UnderwriterToken` contract
- [x] Verify `AssetPool` contract
- [x] Verify `CoveragePool` contract
- [x] Verify `AuctionBidder` contract
- [x] Verify `SignerBondsManualSwap` contract
- [x] Verify `SignerBondsUniswapV2` contract
- [x] Verify `Auction` contract
- [x] Verify `RiskManagerV1` contract
- [x] Verify `RewardsPool` contract
- [x] Verify rewards pool beneficiary contract

# Package publication
Done by Deployment Team
- [x] Publish v1.0.0 package of coverage pools to NPM

# Release notes
Done by Deployment Team
- [x] Publish `solidity/v1.0.0` release notes in `keep-network/coverage-pools`

# Rewards beneficiary approval
Done by Technical Wallet Team
- [x] Approve `RewardsPool` beneficiary on `BatchedPhasedEscrow@0x1b8e50ec9fbf844c3671bc178df8eadfcff831ca` (TX: https://etherscan.io/tx/0x5e61bf48ea689eb9bf3e4938c45d57708b329673d4c90d2f8bd16572a83000a9)

# Test reward funding
Done by Reward Manager
- [x] Top-up coverage pool rewards

# Approve Risk Manager
Done by Community Multisig
- [x] Approve `RiskManagerV1` on `CoveragePool` calling `approveFirstRiskManager` (https://etherscan.io/tx/0xebab8293fdf7cfe1b2a5b6511cad82720e4bd4e6812ff2269c4702a4587acac7)

**Comment by dimpar** [comment]
- After the `Auction` deployment, do we want to include `initialize` step for the `Auction` contract?
- Is auction length has been determined already? `_auctionLength: 1209600`
- I believe we need to determine if we need a new `BatchedPhasedEscrow` based on this [conversation](https://www.flowdock.com/app/cardforcoin/tech/threads/rnSpWYrYTZ_OPcDzEIFKbGHqa93) and change ownership of `RewardsPool` accordingly.

**Comment by lukasz-zimnoch** [comment]
Looks good to me!

**Comment by pdyraga** [comment]
>     * After the `Auction` deployment, do we want to include `initialize` step for the `Auction` contract?

No, we can not even do that because it will fail on `require(!isMasterContract, "Can not initialize master contract");`. Only clones created by the `Auctioneer` can get initialized.

>     * Is auction length has been determined already? `_auctionLength: 1209600`

No, this issue was opened before any work in https://github.com/keep-network/coverage-pools/issues/126 has been done. I've created the Prerequisites section with that issue lined.

>     * Don't we need to transfer ownership for `UnderwriterToken` to the `AssetPool` contract?

Yes, good catch. Added to the list.

**Comment by nkuba** [comment]
Do we want to mention that `UniswapV2Pair` should be deployed as a pre-requisite? https://github.com/keep-network/coverage-pools/blob/72e4055630c9f919444820be1a74a628c7da3990/contracts/SignerBondsUniswapV2.sol#L116-L121

**Comment by pdyraga** [comment]
Based on the conversation in https://github.com/keep-network/coverage-pools/issues/126, I updated the initial auction length to one week.

**Comment by dimpar** [comment]
Don't we need to transfer `AssetPool` ownership  to `CoveragePool`?

**Comment by pdyraga** [comment]
> Don't we need to transfer `AssetPool` ownership to `CoveragePool`?

We do, good catch. Added.

**Comment by nkuba** [comment]
For `AssetsPool` deployment, we have `rewardsManager: Technical Wallet`. The table at the very top contains an entry with `Reward Manager` address. Could you please confirm that it's intended to use `Technical Wallet` instead of `Reward Manager`?

**Comment by nkuba** [comment]
I believe we need to include `CoveragePool` address in `RiskManagerV1` deployment
https://github.com/keep-network/coverage-pools/blob/87a5f22c435648680b96b6e9f20c17ea1d1933fc/contracts/RiskManagerV1.sol#L206-L214

**Comment by pdyraga** [comment]
> For `AssetsPool` deployment, we have `rewardsManager: Technical Wallet`. The table at the very top contains an entry with `Reward Manager` address. Could you please confirm that it's intended to use `Technical Wallet` instead of `Reward Manager`?

Rewards Manager is the owner of Rewards Pool contract. The Technical Wallet was there only because it wasn't clear if we would have the beneficiary ready and deployed. I fixed it - let's assign the deployer address as Rewards Manager and this role will be later transferred to the beneficiary contract:

> Transfer `RewardsPool` ownership to `CoveragePoolBeneficiary`
