### ISSUE TITLE
Constant instead of enum is error-prone

### ISSUE THREAD

**Issue by montyly** [keep-network/coverage-pools#136]
Severity: Informational

## Description
The codebase uses constants for enum-based values. This schema is error-prone and might lead the constant to not be up to date with the enums

For example:
https://github.com/keep-network/coverage-pools/blob/09aa12565ab46a954ab2cb969209e6721bd6b631/contracts/RiskManagerV1.sol#L88-L90

https://github.com/keep-network/tbtc/blob/f8d76ad08a06f1989c9328d81428c4b030226561/solidity/contracts/deposit/DepositStates.sol#L22-L25

## Recommendations
Short term, use an enum in `RiskManagerV1`, and evaluate similar usage of constant in the codebase.

Long term, create interfaces and libraries such that they can be used with multiple codebases and compiler versions

**Comment by tomaszslabon** [comment]
@pdyraga 
I added a [fix](https://github.com/keep-network/coverage-pools/pull/147) in which I replaced constants with enums.
It increased gas consumption a bit and it's slightly more code.

Should we merge it or should we just leave the constants?

**Comment by pdyraga** [comment]
I suggest we leave it as-is. I do agree constants can be error-prone but in this specific case we have tBTC v1 deployed on mainnet, compiled with a specific version of Solidity, and values for those constants can not change. Furthermore, assuming we copy-paste enums, there would be a marginal possibility of Solidity compiler changing how constants are represented and tBTC v1 enums compiled with Solidity 0.5 could not match the ones compiled for coverage pool constants.
