### ISSUE TITLE
[Fix review] receiveApproval might still be vulnerable

### ISSUE THREAD

**Issue by montyly** [keep-network/coverage-pools#137]
See https://github.com/keep-network/coverage-pools/issues/59

The fix proposed was: 
https://github.com/keep-network/coverage-pools/blob/09aa12565ab46a954ab2cb969209e6721bd6b631/contracts/AssetPool.sol#L137

While the original fix looked ok, after more consideration, there is still a risk for a token allowing an **arbitrary data** execution on transfers/approvals. Those are less likely to be used in the system, but might still happen.

One way to mitigate this is to manually review the `token` used, to ensure it does not allow such behavior. This must be documented and checked at deployment.

**Comment by pdyraga** [comment]
Given that no arbitrary tokens will be accepted - the first release will be all about KEEP and the second release might be about a set of carefully selected tokens - I suggest we solve it along with #35 by adding a section to the design doc saying that collateral token accepted needs to be carefully reviewed keeping in mind [token integration checklist](https://github.com/crytic/building-secure-contracts/blob/master/development-guidelines/token_integration.md) and do not allow an arbitrary data execution on transfers/approvals.
