### ISSUE TITLE
Define NPM package structure for deployed artifacts

### ISSUE THREAD

**Issue by pdyraga** [keep-network/coverage-pools#159]
Hardhat and Truffle use a different package structure. We need to decide how our NPM packages should look like so that they can be used from Dashboard. 

Refs: CP-20

**Comment by nkuba** [comment]
For our other projects based on **Truffle**, we export compilation and deployment artifacts in truffle JSON files located in `./artifacts/` directory. It is a symlink to `./build/contracts` which is the default path where Truffle places the artifacts.
The directory structure is flat, artifacts are placed directly under the `./artifacts/` directory (e.g. `./artifacts/KeepToken.json`). The file contains `abi` property that holds ABI generated from contract source code, and deployment details that are held by `network` property with mapping to network ID, e.g.:
```json
{
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "TestToken",
          "type": "address"
        }
      ],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "constructor"
    }
  ],
  "networks": {
    "1101": {
      "events": {},
      "links": {},
      "address": "0x78fecE70FEF77301006e74146B1d823ec7BfC179",
      "transactionHash": "0xdb5da0e5171ce0dd7fd20ddb02fd921fa2863507d6da586401a24390cbc115fb"
    }
  }
}
```
# Hardhat

**Hardhat** with its' plugin [hardhat-deploy](https://github.com/wighawag/hardhat-deploy) produces artifacts in a different way.
## Build artifacts

 Compilation artifacts are separated from deployment artifacts. Compilation artifact goes to a JSON file under `./artifacts/contracts/` directory reflecting the source code directory structure, e.g. `./artifacts/contracts/v2/RewardsPoolV2.sol/RewardPoolV2.json`, the file contains ABI.

<details>
  <summary>Sample Hardhat compilation artifact</summary>

```json
{
  "_format": "hh-sol-artifact-1",
  "contractName": "RewardPoolV2",
  "sourceName": "contracts/v2/RewardsPoolV2.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "assetPool",
          "type": "address"
        }
      ],
      "name": "earned",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x1111",
  "deployedBytecode": "0x2222",
  "linkReferences": {},
  "deployedLinkReferences": {}
}
```
</details>

To distinguish the directory from truffle's `./artifacts` we renamed it to `./build` so these are not confused. https://github.com/keep-network/coverage-pools/blob/0f3a443ea4fc798b7c663b07c1cd4fdabf4a6fc6/hardhat.config.ts#L19

## Deployment artifacts

Deployment artifacts are stored under the `./deployments/<network>` directory, one JSON file per contract, e.g. `./deployments/ropsten/RewardsPool.json`. The artifact contains ABI, deployment transaction hash, and address.
The directory has a `.chainId` file that holds only the chain ID.

<details>
  <summary>Sample Hardhat deployment artifact</summary>

```json
{
  "address": "0x219864Fd9B4eB059FAb41aBE98452F08D58A4946",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "contract IERC20",
          "name": "_rewardToken",
          "type": "address"
        },
        {
          "internalType": "contract AssetPool",
          "name": "_assetPool",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "owner",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "constructor"
    }
  ],
  "transactionHash": "0x3b63f63d6b8d5da83f2facc41443f4b59506186a2781c06cfe8d1eac60aeb40b",
  "receipt": {
    "to": null,
    "from": "0x3d373D872B7BA29d92Ed47CAA8605b4DD6Ec84eF",
    "contractAddress": "0x0D1331622d83eb896D57ECEC55ee46D50c34c1aF",
    "transactionIndex": 0,
    "gasUsed": "4901820",
    "logsBloom": "0x00000000000000000000000004000000000000000000000000800000000000000000000001000000000000000000000001000000000080000000000002000000000000000000000000000000000000000001000000000000000000800000000000000000020000000000022000000800000000000000000000000020000000400420000000000000000000000000000000000000004000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000020000000000000000000000200000000000000000000000",
    "blockHash": "0xcd6f3e516730dc20788df4c594288769e5e3194ea5307baf9e98d415404cdc3b",
    "transactionHash": "0x3b63f63d6b8d5da83f2facc41443f4b59506186a2781c06cfe8d1eac60aeb40b",
    "logs": [
      {
        "transactionIndex": 0,
        "blockNumber": 173654,
        "transactionHash": "0x3b63f63d6b8d5da83f2facc41443f4b59506186a2781c06cfe8d1eac60aeb40b",
        "address": "0x0D1331622d83eb896D57ECEC55ee46D50c34c1aF",
        "topics": [
          "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
          "0x0000000000000000000000000000000000000000000000000000000000000000",
          "0x0000000000000000000000003d373d872b7ba29d92ed47caa8605b4dd6ec84ef"
        ],
        "data": "0x",
        "logIndex": 0,
        "blockHash": "0xcd6f3e516730dc20788df4c594288769e5e3194ea5307baf9e98d415404cdc3b"
      },
      {
        "transactionIndex": 0,
        "blockNumber": 173654,
        "transactionHash": "0x3b63f63d6b8d5da83f2facc41443f4b59506186a2781c06cfe8d1eac60aeb40b",
        "address": "0x219864Fd9B4eB059FAb41aBE98452F08D58A4946",
        "topics": [
          "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
          "0x0000000000000000000000000000000000000000000000000000000000000000",
          "0x0000000000000000000000000d1331622d83eb896d57ecec55ee46d50c34c1af"
        ],
        "data": "0x",
        "logIndex": 1,
        "blockHash": "0xcd6f3e516730dc20788df4c594288769e5e3194ea5307baf9e98d415404cdc3b"
      },
      {
        "transactionIndex": 0,
        "blockNumber": 173654,
        "transactionHash": "0x3b63f63d6b8d5da83f2facc41443f4b59506186a2781c06cfe8d1eac60aeb40b",
        "address": "0x219864Fd9B4eB059FAb41aBE98452F08D58A4946",
        "topics": [
          "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
          "0x0000000000000000000000000d1331622d83eb896d57ecec55ee46d50c34c1af",
          "0x00000000000000000000000052aa72262c904281c49765499f85a774c4598850"
        ],
        "data": "0x",
        "logIndex": 2,
        "blockHash": "0xcd6f3e516730dc20788df4c594288769e5e3194ea5307baf9e98d415404cdc3b"
      }
    ],
    "blockNumber": 173654,
    "cumulativeGasUsed": "4901820",
    "status": 1,
    "byzantium": true
  },
  "bytecode": "0x1111",
  "deployedBytecode": "0x2222"
}
```

</details>

There is also generated deployment export in a single JSON file. That can be convenient for lightweight usage in web apps. The file is named `export.json` and holds ABI and addresses for all deployed contracts. The file contains also details of contracts that were imported as dependencies from other packages. Please see [sample export.json file](https://gist.github.com/nkuba/2ba1a06aa2dfb525fa84ab693627807c).

The directory structure for a package deployed with hardhat:
```

```

**Comment by r-czajkowski** [comment]
My only concern is `deployments/<network>/ `. From the dashboard perspective it could be a little bit tricky because an import for development network would be eg.:
`@keep-network/coverage-pools/deployments/development/AssetPool.json`
but for ropsten: `@keep-network/coverage-pools/deployments/ropsten/AssetPool.json`

I would consider getting rid of the `<network>`, especially we tag npm packages for which network they are for. Eg. `@keep-network/keep-core@1.8.0-ropsten.1`.

**Comment by nkuba** [comment]
Fair point! So for npm package publication we will link `./artifacts/` -> `./deployments/<network>/`.
The `./artifacts/` directory name will be the same as in truffle-style package, the directory will contain `<contract>.json` files. 
The difference will be in the content of the file:
- `abi` property will be available in both truffle and hardhat deployment artifacts in the root,
- `transactionHash` will be available in the root for hardhat (for truffle it is `networks.<chain_id>.transactionHash`,
- `address` will be available in the root for hardhat (for truffle it is `networks.<chain_id>.address`.

**Comment by nkuba** [comment]
@r-czajkowski I',m

**Comment by r-czajkowski** [comment]
> @r-czajkowski I'm wondering if we should publish `deployments/<network>/` directory if we want to have `artifacts/` anyways. This seems like an unnecessary duplication. Thoughts?

Yep, I agree. I believe it's unnecessary because a package will be published only for one network ( `ropsten`, mainnet`).
