### ISSUE TITLE
T Coverage Pool deployment

### ISSUE THREAD

**Issue by dimpar** [keep-network/coverage-pools#200]
Coverage Pool migration proposal: https://forum.threshold.network/t/tip-043-coverage-pool-migration/465

Team | Address
------------ | -------------
**Deployment Team** | `0x123694886DBf5Ac94DDA07135349534536D14cAf`
**Threshold Council** | `0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f`
**Treasury Guild** | `0x71E47a4429d35827e0312AA13162197C23287546`

# Prerequisites
- [x] https://github.com/keep-network/coverage-pools/pull/227
- [x] https://github.com/keep-network/coverage-pools/issues/220

# Deploy smart contracts
All steps done by the Deployment Team
- [x] Create release branch
- [x] Update dependencies to mainnet ones
- [x] Update version to `2.0.0`
- [x] Tag `solidity/v2.0.0` in `keep-network/coverage-pools`
- [x] Sign `solidity/v2.0.0` commit hash
- [x] Deploy `UnderwriterToken` contract (address: `0x007854FdCC9c6F748b435e63745599fb1A0dF843`) with the following parameters:
  - `_name`: `covT underwriter token`
  - `_symbol`: `covT`  
- [x] Deploy `AssetPool` (address: `0x21b86FDC93F23fD52022A283828dF8E808D28D5D`) with the following parameters:
  - `_collateralToken`: `T@0xCdF7028ceAB81fA0C6971208e83fa7872994beE5`
  - `_underwrtierToken`: `UnderwriterToken.address` (deployed in previous step)
  - `rewardsManager`: Deployment Team (temporarily, will be transferred in next steps)
- [x] Transfer `UnderwriterToken` ownership to `AssetPool` (TX: `0xefa3052c96fb054bfd5a377e81b3cabe525e6ddd20937d33200a6f1fcd70c4aa`)
- [x] Deploy `CoveragePool` (address: `0x7D7B622C07f216d99eFc3EfB9Cf71872F46D811A`) with the following parameters:
  - `_assetPool`: `AssetPool.address` (deployed in previous step)
- [x] Transfer `AssetPool` ownership to `CoveragePool` (TX: `0xf4517bfba17413235a8e73c4db4f2d4aaa3a0476f21a49db4983194c2d536f0e`)
- [x] Deploy `BatchedPhasedEscrow` (address: `0xa96AD7889ef29D4978e00B0cB31cD41F77bFD8A6`) with the following parameters:
  - `token`:  `T@0xCdF7028ceAB81fA0C6971208e83fa7872994beE5`  
- [x] Deploy `CoveragePoolBeneficiary` beneficiary (address: `0xE8372cab8d06a607E374cC549d8F68648ef67263`) with the following parameters:
  - `token`:  `T@0xCdF7028ceAB81fA0C6971208e83fa7872994beE5`
  - `rewards`: `assetPool.rewardsPool().address`
- [x] Approve `CoveragePoolBeneficiary` as a beneficiary of `BatchedPhasedEscrow` (TX: `0x8c70cbf5150216a98cf45a14464eb7d53669d5f09d816fb5d157c2cc93a61e99`)
- [x] Transfer ownership of `CoveragePoolBeneficiary` to `BatchedPhasedEscrow` (TX: `0xaaa6899e9524c6fcb914d0f057c1c69341dac4c7644db4d01c0d0dce53b236a8`)
- [x] Transfer `RewardsPool` ownership to `CoveragePoolBeneficiary` (TX: `0x688bb2a0f1ae7c127db99a4f09fe8daf8f02a7c7d827134cb9de7d66797c90fe`)
- [x] Approve Treasury Guild address as the first risk manager of `CoveragePool` (TX: `0x970ebd494cc7eff9b146859d853d36448fb892f015eb963eb887626dca421283`)
- [x] Set `BatchedPhasedEscrow` drawee role to Threshold Council (TX: `0x509704240b2fea44eec8f6a4d6f79dbe2d7b8377e80017ca92f01a6bc0da34ec`)
- [x] Transfer ownership of `BatchedPhasedEscrow` to Threshold Council (TX: `0x34f141eeaf9c81ac77ef876e06dc8c31d936cef15fc8a901a7e8f8111b088349`)
- [x] Transfer `CoveragePool` ownership to Threshold Council (TX: `0xaf49c2dc61893701e08bd651ec45262b5fd1e9e4d700f473979ba862c4a544ca`)

 # Etherscan verification
All steps done by Deployment Team
- [x] Verify `UnderwriterToken` contract
- [x] Verify `AssetPool` contract
- [x] Verify `CoveragePool` contract
- [x] Verify `RewardsPool` contract
- [x] Verify `BatchedPhasedEscrow` contract
- [x] Verify `CoveragePoolBeneficiary` contract

# Package publication
Done by Deployment Team
- [x] Publish v2.0.0 package of coverage pools to NPM

# Release notes
Done by Deployment Team
- [x] Publish `solidity/v2.0.0` release notes in `keep-network/coverage-pools`

# Test deposit
Done by Deployment Team

- [x] Treasury Guild: Deposit 1T into Coverage Pool with `AssetPool.deposit` (Tenderly sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/2f0f40b3-659a-4a95-98f4-868bac818312)

# Test Risk Manager
Done by Deployment Team

- [x] Treasury Guild: Claim 1T coverage with `CoveragePool.seizeAmount` (Tenderly sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/2f0f40b3-659a-4a95-98f4-868bac818312)

# Test reward funding
Done by Deployment Team

- [x] Threshold Council: Top-up coverage pool rewards with 1T with `BatchedPhasedEscrow.withdraw` (Tenderly sim: https://dashboard.tenderly.co/public/safe/safe-apps/simulator/14a580d1-312c-4b3d-9ac6-a5b8cdd4ae79)

# What is not included here

covT underwriter token holders can not yet vote in the token holder DAO. This requires registering coverage pool covT owners as a source of data in DAO contracts

**Comment by pdyraga** [comment]
Test deposit and seize Gnosis TX Builder JSON:

> {"version":"1.0","chainId":"1","createdAt":1675076985536,"meta":{"name":"Transactions Batch","description":"","txBuilderVersion":"1.11.1","createdFromSafeAddress":"0x71E47a4429d35827e0312AA13162197C23287546","createdFromOwnerAddress":"","checksum":"0x1ed770b03ecdf762c8476a7f3e0bb160da08c5a4a153288ff3f394bdcf633d38"},"transactions":[{"to":"0xCdF7028ceAB81fA0C6971208e83fa7872994beE5","value":"0","data":null,"contractMethod":{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"approve","payable":false},"contractInputsValues":{"spender":"0x21b86FDC93F23fD52022A283828dF8E808D28D5D","amount":"1000000000000000000"}},{"to":"0x21b86FDC93F23fD52022A283828dF8E808D28D5D","value":"0","data":null,"contractMethod":{"inputs":[{"internalType":"uint256","name":"amountToDeposit","type":"uint256"}],"name":"deposit","payable":false},"contractInputsValues":{"amountToDeposit":"1000000000000000000"}},{"to":"0x7D7B622C07f216d99eFc3EfB9Cf71872F46D811A","value":"0","data":null,"contractMethod":{"inputs":[{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"amountToSeize","type":"uint256"}],"name":"seizeAmount","payable":false},"contractInputsValues":{"recipient":"0x71E47a4429d35827e0312AA13162197C23287546","amountToSeize":"1000000000000000000"}}]}

**Comment by pdyraga** [comment]
Test reward funding Gnosis TX Builder JSON: 

> {"version":"1.0","chainId":"1","createdAt":1675077138775,"meta":{"name":"Transactions Batch","description":"","txBuilderVersion":"1.11.1","createdFromSafeAddress":"0x71E47a4429d35827e0312AA13162197C23287546","createdFromOwnerAddress":"","checksum":"0x8fc2cb97b73967bedf0b39117c9bb6cb834af47cce67a74930ce90969b4267e9"},"transactions":[{"to":"0xCdF7028ceAB81fA0C6971208e83fa7872994beE5","value":"0","data":null,"contractMethod":{"inputs":[{"internalType":"address","name":"recipient","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transfer","payable":false},"contractInputsValues":{"recipient":"0xa96AD7889ef29D4978e00B0cB31cD41F77bFD8A6","amount":"1000000000000000000"}},{"to":"0xa96AD7889ef29D4978e00B0cB31cD41F77bFD8A6","value":"0","data":null,"contractMethod":{"inputs":[{"internalType":"contract IBeneficiaryContract[]","name":"beneficiaries","type":"address[]"},{"internalType":"uint256[]","name":"amounts","type":"uint256[]"}],"name":"batchedWithdraw","payable":false},"contractInputsValues":{"beneficiaries":"[0xE8372cab8d06a607E374cC549d8F68648ef67263]","amounts":"[1000000000000000000]"}}]}
