### ISSUE TITLE
Reentrancies risks on Auction.takeOffer 

### ISSUE THREAD

**Issue by montyly** [keep-network/coverage-pools#35]
Severity: Undetermined

## Description

`Auction.takeOffer` calls `transferFrom` on an external token without having reeentrancy protection:

https://github.com/keep-network/coverage-pools/blob/49ba7e9dfb5fb421c2b5db18496479d25d374072/contracts/Auction.sol#L146-L157

If the token used has a callback mechanism (such as an ERC777), the destination can re-enter into the contract. 

We did not find a direct way to profit from this, but we considered:
- Re-entering into `takeOffer`: this will lead `_onOffer` to be computed twice with the same value; however we did not find a way for an attacker to profit from it
- Re-entering to execute `earlyClose`, which could lead the system to call `harikari` multiple times. However, this requires privileged accesses, and it is unclear how an attacker would make a profit

## Recommendations
Short term, investigate the risks of reentrancies on tokens transfer. Consider performing the token transfer at the end of the function, or adding reentrancy guard to `takeOffer`. Additionally, take into consideration the reentrancy risks on token transfers when designing `CollateralPool.seizeFunds`.

Long term, be aware of the risks associated with arbitrary tokens, and review the [token integration checklist](https://github.com/crytic/building-secure-contracts/blob/master/development-guidelines/token_integration.md).

**Comment by pdyraga** [comment]
v1 of coverage pools will have only KEEP token accepted and this is a trusted contract.

v2 will probably be multi-asset but tokens will have to be approved by the governance and pass the token integration checklist.
