### ISSUE TITLE
Setting initial value for collateralization threshold level

### ISSUE THREAD

**Issue by dimpar** [keep-network/coverage-pools#64]
This issue is a spin off a PR's comment regarding the default [collateralization threshold value](https://github.com/keep-network/coverage-pools/pull/38#discussion_r627340137). In order to set a value, we need to take into consideration gas usage/price for buying bonds, closing an auction and fluctuation of ETH/BTC price. Initial simulation was made in [this doc](https://docs.google.com/spreadsheets/d/18tDejlULfTN4RG_xgfpcG-K5G8aOwhM6kjlQnPiC0Z4/edit#gid=0)

**Comment by pdyraga** [comment]
Closing in favor of #75.
