### ISSUE TITLE
RiskManagerV1 should validate the deposit being liquidated

### ISSUE THREAD

**Issue by mhluongo** [keep-network/coverage-pools#70]
> RiskManagerV1 should validate that the deposit being liquidated is a
valid deposit. Otherwise, I can create a fake deposit and launch an
auction. From here, I can take the entire auction through the Auction
contract. This'll grant me `portionToSeize` tokens from the coverage
pool. This will also close the auction, which transfers all of the
tBTC to my fake deposit which I can just reclaim. With this, I can
drain the entire AssetPool.

@samczsun

Critical severity, but [there's more!](https://github.com/keep-network/coverage-pools/issues/71)

**Comment by pdyraga** [comment]
The easiest way seems to be inspecting [whether TDT exists](https://github.com/keep-network/tbtc/blob/13eb8046b222173a4449522c782180ec1b0c9f1d/solidity/contracts/system/TBTCDepositToken.sol#L39-L44) but definitely worth confirming with @Shadowfiend before kicking off the implementation. Let's also make sure to implement a set of system tests on a forked chain.
