### ISSUE TITLE
`notifyLiquidation` and `notifyLiquidated` incentives

### ISSUE THREAD

**Issue by pdyraga** [keep-network/coverage-pools#80]
Right now, there are no incentives for anyone to notify the risk manager. The only case when someone would do that non-voluntarily is when they would call`notifyLiquidation` to open an auction and then bid in that auction immediately. 

Ideally, the incentivization mechanism should not grant more rewards from a cookie jar but rather grant assets it "has", which in the case of a single-asset coverage pool is probably COV token. Minting COV without depositing underlying, from the underwriter's perspective, is similar to a coverage claim - the value of their COV is getting lower.

It feels that a fixed governable reward could work better, considering how poorly %-based worked for a few tBTC v1 mechanisms. On the other hand, COV tokens have shifting value relative to the underlying, so it's hard for governance to choose a fee that makes sense over time, in which case maybe governance should instead choose a %.

**Comment by pdyraga** [comment]
In all cases I can think of, a fixed amount looks better to me:
- If the pool TVL grows fast, % is more dangerous and potentially needs to be updated several times as the pool grows.
- The value of COV is changing, true. But % approach does not help, unless we calculate it as % of the underlying deposited in the pool which makes the mechanism complex, and finding the right value by the governance could be hard as well.

**Comment by pdyraga** [comment]
Tagging @mhluongo for a discussion.

**Comment by lukasz-zimnoch** [comment]
@pdyraga I opened a draft with a fixed amount: https://github.com/keep-network/coverage-pools/pull/111. I'd appreciate some opinions about the approach before I continue with the rest.
