### ISSUE TITLE
Review gas cost of operations

### ISSUE THREAD

**Issue by pdyraga** [keep-network/coverage-pools#81]
Review gas limit required and the actual gas spent of the public API functions. See if they are acceptable and if any optimizations are needed. Especially:
- `RiskManagerV1.notifyLiquidation`
- `RiskManagerV1.notifyLiquidated` 
- `AssetPool.deposit`
- `AssetPool.initiateWithdrawal`
- `AssetPool.completeWithdrawal`
- `Auction.takeOffer` for a partial offer and fully filled auction
- `AuctionBidder.takeOfferWithMin`
- `SignerBondsUniswapV2.swapSignerBondsOnUniswapV2`

**Comment by dimpar** [comment]
Running system tests and checking `txReceipt.gasUsed`
`RiskManagerV1.notifyLiquidation` - `391623` gas

**Comment by pdyraga** [comment]
Those are gas estimates as used in the gas limit but the actual gas used can be lower, correct?

**Comment by dimpar** [comment]
> Those are gas estimates as used in the gas limit but the actual gas used can be lower, correct?

These are the actual gas used, not gas limit

**Comment by pdyraga** [comment]
There is ~127 621 difference between unit and system tests for `RiskManger.notifyLiquidation`. Is it some very expensive tBTC v1 Deposit function call?

**Comment by dimpar** [comment]
Yes, it seems the difference comes from `liquidateDeposit()` when purchasing a deposit with surplus.
- gas used in the unit tests for _purchasing and withdrawing funds_ from deposit is around `107k`
- gas used in the system tests for the above is around `254k`

Gas varies depending on a unit/system test, but the biggest difference comes from calling `deposit.purchaseSignerBondsAtAuction()` and `deposit.withdrawableAmount()`

This is the code that I used for gas usage:
```
        uint256 startGas = gasleft();
        // code
        uint256 gasUsed = startGas - gasleft();
        console.log("gasUsed: ", gasUsed);
```

**Comment by pdyraga** [comment]
If not purchasing from surplus and doing `notifyLiquidation` call, what the gas limit / gas used is going to be?

**Comment by dimpar** [comment]
> If not purchasing from surplus and doing `notifyLiquidation` call, what the gas limit / gas used is going to be?

Latest `notifyLiquidation` will use from ~378722 to ~443722 gas depending on notifier rewards setup. If buying with surplus, the gas usage should be lower, cause:
```
       // (~263684gas)
       if (tbtcSurplus >= lotSizeTbtc) {
            tbtcSurplus -= lotSizeTbtc;
            liquidateDeposit(deposit);
            return;
        }
```
 consumes less gas than:

```
        // (~296748gas)
        address auctionAddress = createAuction(tbtcToken, lotSizeTbtc, auctionLength);
        depositToAuction[depositAddress] = auctionAddress;
        auctionToDeposit[auctionAddress] = depositAddress;
```

Gas limit is kinda tricky in hardhat. If not setting manually like we do in a couple of places like [here](https://github.com/keep-network/coverage-pools/blob/main/test/system/uniswap-v2.test.js#L75) it will show >1M. But if you do it like in a example, ie setting it programatically, than it is the same as gasUsed.

**Comment by pdyraga** [comment]
I think I am comfortable with all the numbers except these for `notifyLiquidation` and `takeOffer` where I think we need to spend more time to identify gas usage for individual cases. Ranges do not say that much, 300k is much lower than 450k.

So what I'd recommend we check:
- gas limit and gas used for `notifyLiquidation` without surplus
- gas limit and gas used for `notifyLiquidation` with surplus
- gas limit and gas used for partial `takeOffer` with 100% bonds on offer
- gas limit and gas used for last partial `takeOffer` (closing the auction) with 100% bonds on offer
- gas limit and gas used for full `takeOffer` with 100% bonds on offer
- gas limit and gas used for partial `takeOffer` with less than 100% bonds on offer
- gas limit and gas used for last partial `takeOffer` (closing the auction) with less than 100% bonds on offer
- gas limit and gas used for full `takeOffer` with less than 100% bonds on offer

Checking these will let us see what is the gas cost for most common cases. If the most common case is 300k for `notifyLiquidation`, we should be fine. If the most common case is 450k, it could be a hard-to-swallow pill and the incentive will have to be adjusted accordingly.

**Comment by dimpar** [comment]
> * gas limit and gas used for `notifyLiquidation` without surplus

- gas used: `362911`
- min gas limit set programatically: `362911`
- gas limit returned by Hardhat: `11472680`

> * gas limit and gas used for `notifyLiquidation` with surplus and less than 100% bonds on offer
- gasUsed: `275054`
- min gas limit set programatically: `~330000`
- gas limit returned by Hardhat: `11472680`

> * gas limit and gas used for `notifyLiquidation` with surplus and 100% bonds on offer
- gasUsed: `160682`
- min gas limit set programatically: `~220000`
- gas limit returned by Hardhat: `11472680`

`100% bonds on offer` meaning [24h](https://github.com/keep-network/tbtc/blob/main/solidity/contracts/system/TBTCConstants.sol#L26) elapsed after the tbtc deposit auction has started

TODO: `takeOffer`

**Comment by pdyraga** [comment]
> when liquidation notifier reward amount is set

Is it with or without surplus? The cost difference should not be that significant, 429k is worrisome.

**Comment by dimpar** [comment]
> > when liquidation notifier reward amount is set
> 
> Is it with or without surplus? The cost difference should not be that significant, 429k is worrisome.

This is without surplus

**Comment by pdyraga** [comment]
👍🏻
