### ISSUE TITLE
System tests

### ISSUE THREAD

**Issue by pdyraga** [keep-network/coverage-pools#83]
We have a set of system tests working on Hardhat Network on a forked mainnet chain. 
At the start, the fork is being reset to the specific starting block which determines the initial test state. Tests use real TBTC token contract and Deposit contract. Currently, the following scenarios are covered:

- Liquidation happy path with a fully-filled auction. Deposit is in a liquidation state, bidder takes the entire auction. We assert that the deposit has been liquidated, auction is closed, signer bonds are processed, and reasonable amount of gas is consumed.
- Deposit validation. It is not possible to open an auction for a fake deposit.
- Uniswap V2 ETH->KEEP bonds swap happy path. We assert signer bonds are properly swapped and sent to the asset pool. We assert a reasonable amount of gas is consumed.

This issue aims at identifying additional system test scenarios and implementing them.

**Comment by pdyraga** [comment]
Proposed new scenarios:
- Auction fully filled in one shot. Assert the correct amount has been seized from the pool.
- Auction fully filled but using multiple partial take offers. Assert the correct amount has been seized from the pool.
- Auction liquidated outside of cov pools. Assert it is not possible to take an auction (fully filled and partial offer).

... define more please.

**Comment by tomaszslabon** [comment]
Perhaps this scenario:
- Auction fully filled after `auctionLength`. Ensure the whole pool was seized and transferred to the bidder.

**Comment by dimpar** [comment]
All of the above scenarios were added in the table below except the last one, which I think overlaps with other tests. A test scenario was added covering buying deposit with surplus funds.

For more tests scenarios I propose to fill out this table to track what we already have and what should be added.

| Testing scenario                                            | Assertion                                                                                                                                                                                                    | Is implemented |
|-------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------|
| Liquidation happy path with a fully-filled auction          | Deposit is in a liquidation state, bidder takes the entire auction. We assert that the deposit has been liquidated, auction is closed, signer bonds are processed, and reasonable amount of gas is consumed. | Yes            |
| Deposit validation                                          | It is not possible to open an auction for a fake deposit.                                                                                                                                                    | Yes            |
| Uniswap V2 ETH->KEEP bonds swap happy path                  | Signer bonds are properly swapped and sent to the asset pool. We assert a reasonable amount of gas is consumed.                                                                                              | Yes            |
| Auction fully filled in one shot                            | Assert the correct amount has been seized from the pool.                                                                                                                                                     | No             |
| Auction fully filled but using multiple partial take offers | Assert the correct amount has been seized from the pool.                                                                                                                                                     | No             |
| Auction liquidated outside of cov pools.                    | Assert it is not possible to take an auction (fully filled and partial offer).                                                                                                                               | WIP            |
| Auction fully filled after auctionLength has elapsed.       | Assert the whole pool was seized and transferred to the bidder.                                                                                                                                              | No             |
| Risk manager buys a deposit with a surplus TBTC funds       | Assert that no auction was created, deposit is liquidated & bonds are in swap strategy contract.                                                                                                             | WIP            |

**Comment by pdyraga** [comment]
As a side note, I think we should reference this issue from integration tests as well, especially that we are removing/adding them on the expense of system tests.

**Comment by pdyraga** [comment]
In all scenarios, we are dealing with liquidating deposit because of a redemption signature timed out. We could add a test that it is possible to notify liquidated for undercollateralized deposit.

**Comment by michalinacienciala** [comment]
Could we add an assertion for Testing scenarios 1 and 4 that would check the balance of coverage pool after auction gets filled?

**Comment by michalinacienciala** [comment]
Regarding scenario 5 - I don't understand the "surplus that was left from an opened auction" part - will we have any surplus? There were no bidders (as far as I understand).

Btw, perhaps we could merge scenarios 5 and 7?
Steps:
1. Auction opened for deposit
2. Deposit liquidated outside cov pool
3. Assert attempt to take auction (fully filled) is reverted.
4. Assert attempt to take auction (partially filled) is reverted.
5. Inform cov pool (notifyLiquidated()) on a deposit that was liquidated outside the cov pool
6. A cov pool auction for that deposit is closed now

**Comment by tomaszslabon** [comment]
@michalinacienciala 

> Could we add an assertion for Testing scenarios 1 and 4 that would check the balance of coverage pool after auction gets filled?

Sure, we added assertions:
- "the amount of tokens in the asset pool decreased by the amount received by the bidder " for test 1.
- "the asset pool is empty" for test 4.

So in other words, we check that the proper amount of collateral tokens was removed from the Asset Pool (which is the contract that holds collateral tokens in the Coverage Pool).

**Comment by dimpar** [comment]
> Regarding scenario 5 - I don't understand the "surplus that was left from an opened auction" part - will we have any surplus? There were no bidders (as far as I understand).

There are 2 bidders in this scenario. In short.. `bidder1` takes a partial offer (say 3 TBTC) in `auction1` which was opened for `deposit1` - 5 TBTC. But a while after `bidder2` bought `deposit1` outside the cov pool. 3 TBTC is what left on the contract, ie. surplus.  Then comes another liquidation for `deposit2` - 1 TBTC. Contract has 3 TBTC which means it can buy `deposit2` without opening an auction.  At the end there will be 2 TBTC left on contract. By saying "surplus that was left from an opened auction" in this example I mean surplus from `auction1` which is already closed.

**Comment by michalinacienciala** [comment]
> > Regarding scenario 5 - I don't understand the "surplus that was left from an opened auction" part - will we have any surplus? There were no bidders (as far as I understand).
> 
> There are 2 bidders in this scenario. In short.. `bidder1` takes a partial offer (say 3 TBTC) in `auction1` which was opened for `deposit1` - 5 TBTC. But a while after `bidder2` bought `deposit1` outside the cov pool. 3 TBTC is what left on the contract, ie. surplus. Then comes another liquidation for `deposit2` - 1 TBTC. Contract has 3 TBTC which means it can buy `deposit2` without opening an auction. At the end there will be 2 TBTC left on contract. By saying "surplus that was left from an opened auction" in this example I mean surplus from `auction1` which is already closed.

That sounds like a description of scenario 6 - what's the difference between them?

**Comment by dimpar** [comment]
> > > Regarding scenario 5 - I don't understand the "surplus that was left from an opened auction" part - will we have any surplus? There were no bidders (as far as I understand).
> > 
> > 
> > There are 2 bidders in this scenario. In short.. `bidder1` takes a partial offer (say 3 TBTC) in `auction1` which was opened for `deposit1` - 5 TBTC. But a while after `bidder2` bought `deposit1` outside the cov pool. 3 TBTC is what left on the contract, ie. surplus. Then comes another liquidation for `deposit2` - 1 TBTC. Contract has 3 TBTC which means it can buy `deposit2` without opening an auction. At the end there will be 2 TBTC left on contract. By saying "surplus that was left from an opened auction" in this example I mean surplus from `auction1` which is already closed.
> 
> That sounds like a description of scenario 6 - what's the difference between them?

Yea.. my bad, this is a description of scenario 6 actually, not 5. After taking a closer look, with just a bit of refactoring I think we can merge these 2 tests. Here's a [PR](https://github.com/keep-network/coverage-pools/pull/117)

**Comment by dimpar** [comment]
> Btw, perhaps we could merge scenarios 5 and 7?
> Steps:
> 
> 1. Auction opened for deposit
> 2. Deposit liquidated outside cov pool
> 3. Assert attempt to take auction (fully filled) is reverted.
> 4. Assert attempt to take auction (partially filled) is reverted.
> 5. Inform cov pool (notifyLiquidated()) on a deposit that was liquidated outside the cov pool
> 6. A cov pool auction for that deposit is closed now

A couple of tests evolved over time but yes, I think we can safely merge `deposit-liquidated-externally.test.js` to `surplus-for-auction.test.js` since the tests prerequisites are very similar. [PR](https://github.com/keep-network/coverage-pools/pull/129) is opened

**Comment by tomaszslabon** [comment]
> In all scenarios, we are dealing with liquidating deposit because of a redemption signature timed out. We could add a test that it is possible to notify liquidation for undercollateralized deposit.
@pdyraga, in one test [surplus-for-auction.test.js](https://github.com/keep-network/coverage-pools/blob/main/test/system/surplus-for-auction.test.js) we liquidate an undercollateralized deposit [0xfc9c50fd44879bd7085edd311bc8e2b7d3e41595](https://allthekeeps.com/deposit/0xfc9c50fd44879bd7085edd311bc8e2b7d3e41595) via cov pools.
That's why we decided not to include a separate test for this scenario.

**Comment by dimpar** [comment]
All the comments are addressed and all the system tests were merged into the `main` branch.

**Comment by pdyraga** [comment]
Do we know why there are such significant differences in gas limit and gas spent for those two `takeOffer` calls? They both seem to be the last ones for the auction so they need to purchase bonds.

https://github.com/keep-network/coverage-pools/blob/fb7e0d5e599290d23ab0d88554cb593b84b03294/test/system/liquidation.test.js#L173-L178

https://github.com/keep-network/coverage-pools/blob/fb7e0d5e599290d23ab0d88554cb593b84b03294/test/system/liquidation-multiple-take-offers.test.js#L175-L180

**Comment by dimpar** [comment]
> Do we know why there are such significant differences in gas limit and gas spent for those two `takeOffer` calls? They both seem to be the last ones for the auction so they need to purchase bonds.
> 
> https://github.com/keep-network/coverage-pools/blob/fb7e0d5e599290d23ab0d88554cb593b84b03294/test/system/liquidation.test.js#L173-L178
> 
> https://github.com/keep-network/coverage-pools/blob/fb7e0d5e599290d23ab0d88554cb593b84b03294/test/system/liquidation-multiple-take-offers.test.js#L175-L180

**Comment by pdyraga** [comment]
Let's check what exactly it is, it is also related to #81 where we noted that `notifyLiquidation` in some cases is too expensive.

**Comment by dimpar** [comment]
> Let's check what exactly it is, it is also related to #81 where we noted that `notifyLiquidation` in some cases is too expensive.

It looks like it is related to the deposit AUCTION_DURATION. If more than 24h passed from the [Liquidation Started: Signer Timeout](https://allthekeeps.com/deposit/0x8495732aecd7f132eaab61f64858ccc73475973f) then `purchaseSignerBondsAtAuction()` cost ~110k less. That was the case in `liquidation-multiple-take-offers.test.js` where we wait > 24hours but for the cov pool auction, which happens to be the same as tbtc auction duration.
