### ISSUE TITLE
Simplify withdrawal mechanism?

### ISSUE THREAD

**Issue by pdyraga** [keep-network/coverage-pools#89]
As currently implemented, the coverage pool withdrawal mechanism works as follows:
- Underwriter deposited into the pool. Their KEEP is in the pool earning rewards and is a subject of a potential claim.
- Underwriter initiated withdrawal. Their KEEP is in the pool earning rewards and is a subject of a potential claim.
- Underwriter is waiting for 2 weeks withdrawal delay.  Their KEEP is in the pool earning rewards and is a subject of a potential claim.
- The 2-week withdrawal delay passed. There is 1 week graceful withdrawal time for which the underwriter can complete the withdrawal. For the entire withdrawal delay time, until the underwriter completes the withdrawal, their KEEP is in the pool earning rewards and is a subject of a potential claim.
- In the case underwriter forgot (or decided not to) complete the withdrawal during the graceful withdrawal time, they have 9 weeks (63 days) before the hard withdrawal timeout. For all that time, until the underwriter completes the withdrawal, their KEEP is in the pool earning rewards and is a subject of a potential claim. For all that time. until the underwriter completes the withdrawal, KEEP and rewards accrued are getting slowly seized by the pool, proportionally to the time passed since the graceful withdrawal time ended.
- If they do not complete withdrawal after 63 days, they lose all of their tokens - they are seized by the pool.

AAVE approach for unstaking is:
- Activate cooldown, wait for the cooldown period, currently 10 days
- Complete unstaking after the cooldown period. One has 2 days for that (governable). If they do not complete within 2 days, they need to activate cooldown again and wait for the cooldown period again.

Both approaches have their pros and cons. 

What I personally do not like about the approach with "returning to normal staking" compared to the current implementation, is that in case the withdrawal has not been completed after the cooldown period, for the entire two-day unstake period, underwriters free-ride the system. They earn rewards but can withdraw at any time, especially before a claim. Smart underwriters could be activating the unstake in a loop. They cannot withdraw for 10 days but can withdraw at any time for 2 days, so they got 16% of the staking time as risk-free. On the other hand, the same situation is for our current implementation except that they need to execute two more transactions that do cost gas: withdraw and deposit again. It is not cost-free but there might be a situation when the low gas cost makes this attack more profitable.

Another thing I like about the current implementation is that timeouts are non-governable. It is clear from the beginning what are the timeouts and it is not possible to change the graceful withdrawal timeout to e.g. 10 seconds.  Even if someone forgets to withdraw or can not do that because of a local gas price peak, they have a week to do that, and even if they do not complete withdrawal within that time, their tokens are slowly getting seized which is not ideal but also not terrible assuming they withdraw early. 

What I do not like about the current approach is that it is complex to explain and we still need to model, how many tokens need to be burned over time after the graceful withdrawal period ended so that staying in the pool is not profitable.

If we decide to simplify the approach, I think we need to make the graceful withdrawal time shorter and governable, e.g. 12 days cooldown, 2 days withdrawal.

Waiting for more thoughts from the community.

**Comment by Estebank97** [comment]
"There is 1 week graceful withdrawal time for which the underwriter can complete the withdrawal. For the entire withdrawal delay time, until the underwriter completes the withdrawal, their KEEP is in the pool earning rewards and is a subject of a potential claim."
Why not combine both approaches ? After this cool down period if underwriter chooses (or forgets) to withdraw then their KEEP "returns to normal staking" instead of entering this 9 week seizure period ?

**Comment by liz-shinn** [comment]
The Aave approach looks like it provides a safer user experience. The cons in the Aave approach are the risk of a high gas cost when your funds are returned if you don't claim within the grace period, but that is a comparably lower risk to the potential of losing the entire deposited token balance.

I can see several instances where a user might not claim their tokens within the time limit and run the risk of losing their full token balance. For example, they:
A. Don't fully understand the coverage pools claim process
B. Don't have access to their account for xyz reason (lost their ledger, were hospitalized, traveling)
C. Forgot

>If we decide to simplify the approach, I think we need to make the graceful withdrawal time shorter and governable, e.g. 12 days cooldown, 2 days withdrawal.

This seems like a reasonable compromise to me.

**Comment by nahuus123** [comment]
I'm for the AAVE approach. I think it's easier to understand and explain. Also the fact that if you're not able to withdraw for unforeseen circumstances, and eventually get penalized for that, could be a bad user experience / reason for people to opt out.

Also the fact mentioned above of having the funds flow back into the pool is a pro for me.

**Comment by benlongstaff** [comment]
> If they do not complete withdrawal after 63 days, they lose all of their tokens - they are seized by the pool.

This seems like a very sharp edge to me, someone could end up in hospital for a couple of months and come back to find they had lost all their tokens.

**Comment by tomaszslabon** [comment]
@pdyraga 
Here is a zip file with charts showing how collateralization level changed over time (between deposit creation and liquidation initiation) for all deposits liquidated due to undercollateralization. The charts are sorted by the amount of time between deposit creation and liquidation initiation (the longest-lived deposits are first). There is also a file
`undercollaterized-liquidations.json` with all the deposits listed.  Perhaps they could be useful in determining the value of the cool down parameter.

**Comment by pdyraga** [comment]
I was looking at historical liquidations and 14 days withdrawal delay could not be enough in all cases. Of course, those are just historical data and there is no guarantee future will look similar but if something already happened there is a chance it will happen again and we should be prepared.

All liquidations we had on mainnet can be reduced to three cases:
- liquidations around ~Nov 5th,
- liquidations around ~Nov 17th,
- liquidations around ~Dec 26th.

If I were coverage pool underwriter having a strategy to withdraw all my funds when it starts getting risky setting the threshold at 135% collateralization level, two week withdrawal period would not stop me from escaping the pool for Nov 17th liquidation. 

![aaa1](https://user-images.githubusercontent.com/4712360/123096015-f3468000-d42e-11eb-8126-4a3672688f35.png)

![aaa2](https://user-images.githubusercontent.com/4712360/123096032-f7729d80-d42e-11eb-9551-7f43023d4a94.png)

![aaa3](https://user-images.githubusercontent.com/4712360/123096046-fa6d8e00-d42e-11eb-8c44-7e5ac4328981.png)

We can not stop people from withdrawing but the whole point of a coverage pool is to be with the pool when it is sunny outside, everyone is happy, and earning rewards, and be with the pool when the storm is coming so that there is that last-chance insurance. We do not want to make it easy for underwriters trying to escape when they see a small cloud on the sky and being interested in a free ride on everyone else's shoulders. 21 days withdrawal delay feels like a good tradeoff.
